package com.example.mygreedaotest.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.day10lianxi.util.DataDbBean;

import com.example.mygreedaotest.dao.DataDbBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dataDbBeanDaoConfig;

    private final DataDbBeanDao dataDbBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dataDbBeanDaoConfig = daoConfigMap.get(DataDbBeanDao.class).clone();
        dataDbBeanDaoConfig.initIdentityScope(type);

        dataDbBeanDao = new DataDbBeanDao(dataDbBeanDaoConfig, this);

        registerDao(DataDbBean.class, dataDbBeanDao);
    }
    
    public void clear() {
        dataDbBeanDaoConfig.clearIdentityScope();
    }

    public DataDbBeanDao getDataDbBeanDao() {
        return dataDbBeanDao;
    }

}
